---
title: "IGT Analyses"
author: "T.L"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}

packrat::init()

```


```{r, Libraries, message = FALSE}

#### Libraries ####

library(tidyverse)

library(janitor)

library(rstatix)

library(sjstats)

library(pwr)

library(ggpubr)

library(afex)

library(emmeans)

library(ggpubr)

library(Hmisc)

```

```{r}
# Read in and clean data file

df_igt <- read_csv("IGT_Behav_Data_5blocks.csv")

df_igt <- clean_names(df_igt)


df_igt <- df_igt %>% rename(advice_condition = advice_condition_15)

df_igt <- df_igt %>% rename(advice_condition_1 = advice_condition_16)

# Prepare data to check the demographic differences between age groups.

# Set and reorder factors

df_igt$age_group <- as.factor(df_igt$age_group)

df_igt <- df_igt %>% 
  reorder_levels(age_group, order = c("Young", "Older"))

df_igt$advice_condition <- as.factor(df_igt$advice_condition)

df_igt <- df_igt %>% 
  reorder_levels(advice_condition, order = c("None", "A", "B"))

df_igt$advice_condition_1 <- as.factor(df_igt$advice_condition_1)

df_igt <- df_igt %>% 
  reorder_levels(advice_condition_1, order = c("None", "Bad"))

df_igt$gender <- as.factor(df_igt$gender)

# Mean and SD for age

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(age)

# Gender in each age group


df_igt %>% 
  group_by(age_group, gender) %>% 
  get_summary_stats(age, type = "mean")


```



```{r}
###### Education ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(education, type="mean_sd")

# Box plot education

bxp_edu <- ggboxplot(
  df_igt, x = "age_group", y = "education",
  ylab = "Years of Education", xlab = "Age Groups", add = "jitter"
  )
bxp_edu

# Identify outliers in Education 

df_igt %>%
  group_by(age_group) %>%
  identify_outliers(education)

# 3 extremes: participants 105,123 and 240 (rows 44, 50 and 88)

# Compute Shapiro wilk test by groups

df_igt %>% 
  group_by(age_group) %>%
  shapiro_test(education)


# Levene's test

df_igt %>% levene_test(education ~ age_group)

# Assumption met

# Compute Weltch's test 

edu.test <- df_igt %>% 
  t_test(education ~ age_group) %>%
  add_significance()
edu.test

# Significant difference between the age groups

# Get the effect size 

df_igt %>%  cohens_d(education ~ age_group, var.equal = TRUE)

```



```{r}
## Re-run Education analyses with the 3 extreme outliers removed ##

edu_outliers_removed <- df_igt[-c(44, 50, 88),]

# T-test with outliers removed 

edu.test2 <- edu_outliers_removed %>% 
  t_test(education ~ age_group) %>%
  add_significance()
edu.test2

# Does not change the significance

```


```{r}
###### Health ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(current_health_rating, type = "mean_sd")

# Boxplots of health ratings 

bxp_health <- ggboxplot(
  df_igt, x = "age_group", y = "current_health_rating", 
  ylab = "Current Health Rating", xlab = "Age Groups", add = "jitter"
  )
bxp_health

# Identify outliers in health ratings

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(current_health_rating)

# No extreme outliers identified

# Shapiro Wilks test by groups 

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(current_health_rating)

# Significant

# Levene's test

df_igt %>% levene_test(current_health_rating ~ age_group)

# Assumption met

# Compute Weltch's test 

health.test <- df_igt %>% 
  t_test(current_health_rating ~ age_group) %>%
  add_significance()
health.test

# No significant difference

# Effect size for health 

df_igt %>%  cohens_d(current_health_rating ~ age_group, var.equal = FALSE)

```


```{r}
###### Depression ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(depression_score, type = "mean_sd")

# Boxplots of depression scores

bxp_dep <- ggboxplot(
  df_igt, x = "age_group", y = "depression_score", 
  ylab = "Depression", xlab = "Age Groups", add = "jitter"
  )
bxp_dep

# Get outliers 

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(depression_score)

# No extreme outliers identified

# Shapiro Wilks test by groups

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(depression_score)

# Significant... But >30 in each group. 

# Levene's test

df_igt %>% levene_test(depression_score~age_group)

# Assumption met

# T-test 

dep.test <- df_igt %>% 
  t_test(depression_score ~ age_group) %>%
  add_significance()
dep.test

# Significant difference between age groups

# Depression score effect size

df_igt %>%  cohens_d(depression_score ~ age_group, var.equal = FALSE)


```


```{r}
###### Anxiety scores ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(anxiety_score, type = "mean_sd")

# Boxplots of anxiety scores

bxp_anx <- ggboxplot(
  df_igt, x = "age_group", y = "anxiety_score", 
  ylab = "Anxiety", xlab = "Age Groups", add = "jitter"
  )
bxp_anx

# Identify anxiety outliers 

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(anxiety_score)

# 2 extremes: participants 101, 105, rows 41 and 44

# Shapiro Wilks test by groups

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(anxiety_score)

# Significant

# Levene's test

df_igt %>% levene_test(anxiety_score~age_group)

# Assumption met

# Anxiety t test

anx.test <- df_igt %>% 
  t_test(anxiety_score ~ age_group) %>%
  add_significance()
anx.test

# Significant difference between age groups

# Effect size

df_igt %>%  cohens_d(anxiety_score ~ age_group, var.equal = FALSE)


```


```{r}

## Re-run anxiety analyses with the 2 extreme outliers removed ##

anx_outliers_removed <- df_igt[-c(41, 44),]

# T-test with outliers removed 

anx.test2 <- anx_outliers_removed %>% 
  t_test(anxiety_score ~ age_group) %>%
  add_significance()
anx.test2

# Still significant

```


```{r}
###### Stress scores ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(stress_score, type = "mean_sd")

# Stress boxplots 

bxp_stress <- ggboxplot(
  df_igt, x = "age_group", y = "stress_score", 
  ylab = "Stress", xlab = "Age Groups", add = "jitter"
)
bxp_stress

## Identify outliers ##

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(stress_score)

# None!

# Shapiro Wilks test on stress 

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(stress_score)

# Significant for older adults

# Levene's test on stress 

df_igt %>% levene_test(stress_score~age_group)

# Assumption met

# Compute t test on stress

stress.test <- df_igt %>% 
  t_test(stress_score ~ age_group) %>%
  add_significance()
stress.test

# Effect sizes for stress

df_igt %>%  cohens_d(stress_score ~ age_group, var.equal = FALSE)

```


```{r}

###### Digit span forwards / Short-term memory ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(dig_span_f, type = "mean_sd")

# Box plots for digit span forwards

bxp_dig_f <- ggboxplot(
  df_igt, x = "age_group", y = "dig_span_f", 
  ylab = "Short term memory", xlab = "Age Groups", add = "jitter"
)
bxp_dig_f

# Digit span forwards outliers 

df_igt %>% 
  group_by(age_group) %>%
  identify_outliers(dig_span_f)

# None found

# Shapiro Wilks for digit span forwards

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(dig_span_f)

# Significant

# Levene's test for short term memory

df_igt %>% levene_test(dig_span_f~age_group)

# Significant - Assumption violated

# T Test for digit span forwards

dig.f.test <- df_igt %>% 
  t_test(dig_span_f ~ age_group) %>%
  add_significance()
dig.f.test

# Effect size

df_igt %>%  cohens_d(dig_span_f ~ age_group, var.equal = FALSE)

```


```{r}

###### Digit span backwards / Working memory ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(dig_span_b, type ="mean_sd")

# Boxplots for digit span backwards

bxp_dig_b <- ggboxplot(
  df_igt, x = "age_group", y = "dig_span_b", 
  ylab = "Working memory", xlab = "Age Groups", add = "jitter"
)
bxp_dig_b

# Look for outliers in digit span backwards

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(dig_span_b)

# No extremes

# Shapiro Wilks on digit span backwards

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(dig_span_b)

# Significant

# Levene's test on working memory

df_igt %>% levene_test(dig_span_b~age_group)

# not significant

# Compute t test

dig.b.test <- df_igt %>% 
  t_test(dig_span_b ~ age_group) %>%
  add_significance()
dig.b.test

# Effect size

df_igt %>%  cohens_d(dig_span_b ~ age_group, var.equal = FALSE)


```


```{r}
###### Matrices / Fluid intelligence ######

# Ms and SDs by age group

df_igt %>% 
  group_by(age_group) %>% 
  get_summary_stats(matrices, type="mean_sd")

# Matrices boxplots 

bxp_mats <- ggboxplot(
  df_igt, x = "age_group", y = "matrices", 
  ylab = "Fluid Intelligence", xlab = "Age Groups", add = "jitter"
)
bxp_mats

# Outliers for matrices

df_igt %>% 
  group_by(age_group) %>% 
  identify_outliers(matrices)

# 4 extremes: P 206, 228, 253, 262 (rows: 58, 76, 100, 109)

# Shapiro wilks on matrices 

df_igt %>%
  group_by(age_group) %>%
  shapiro_test(matrices)

# Significant

# Levene's test 

df_igt %>% levene_test(matrices~age_group)

# Assumption violated

# Compute t test for matrices

mat.test <- df_igt %>% 
  t_test(matrices ~ age_group) %>%
  add_significance()
mat.test

# Significant difference

# Effect sizes for matrices 

df_igt %>%  cohens_d(matrices ~ age_group, var.equal = FALSE)

```


```{r}

## Re-run matrices analyses with extreme outliers removed ##

mat_outliers_removed <- df_igt[-c(58, 76, 100, 109),]

# T-test with outliers removed 

mat.test2 <- anx_outliers_removed %>% 
  t_test(matrices ~ age_group) %>%
  add_significance()
mat.test2

# Still significant

```


```{r}
###### Analyses of IGT blocks ######

# Prep data

df_igt <- df_igt %>%
rename(decka_block1 = deck_a_block_1,
deckb_block1 = deck_b_block_1,
deckc_block1 = deck_c_block1,
deckd_block1 = deck_d_block1,
decka_block2 = deck_a_block_2,
deckb_block2 = deck_b_block_2,
deckc_block2 = deck_c_block2,
deckd_block2 = deck_d_block2,
decka_block3 = deck_a_block_3,
deckb_block3 = deck_b_block_3,
deckc_block3 = deck_c_block3,
deckd_block3 = deck_d_block3,
decka_block4 = deck_a_block_4,
deckb_block4 = deck_b_block_4,
deckc_block4 = deck_c_block4,
deckd_block4 = deck_d_block4,
decka_block5 = deck_a_block_5,
deckb_block5 = deck_b_block_5,
deckc_block5 = deck_c_block5,
deckd_block5 = deck_d_block5
)


# Update ID variable to factor

df_igt$id <- as.factor(df_igt$id)

# Convert to long form data

df_igt_bad_long <- pivot_longer(df_igt, cols = c(28:37), 
                         names_to = c("deck","block"), 
                         names_sep = "_", 
                         values_to = "proportion_selected")


df_igt_bad_long$deck <- as.factor(df_igt_bad_long$deck)

df_igt_bad_long$block <- as.factor(df_igt_bad_long$block)

df_igt_bad_long$id <- as.factor(df_igt_bad_long$id)


df_igt_bad_long <- reorder_levels(df_igt_bad_long, block, order = c("block1", "block2", "block3",
                                                                    "block4", "block5"))
### Summary stats on bad deck selections ###

df_igt_bad_long %>% 
  group_by(age_group, advice_condition) %>% 
  get_summary_stats(proportion_selected, type = "mean_sd")

# Check variance between samples sizes - Blanca et al., 2018.

young_var_none <- var(df_igt_bad_long$advice_condition=="None" & df_igt_bad_long$age_group=="Young", na.rm=TRUE)

young_var_none

young_var_A <- var(df_igt_bad_long$advice_condition=="A" & df_igt_bad_long$age_group=="Young", na.rm=TRUE)

young_var_A

young_var_B <- var(df_igt_bad_long$advice_condition=="B" & df_igt_bad_long$age_group=="Young", na.rm=TRUE)

young_var_B

older_var_none <- var(df_igt_bad_long$advice_condition=="None" & df_igt_bad_long$age_group=="Older", na.rm=TRUE)

older_var_none

older_var_A <- var(df_igt_bad_long$advice_condition=="A" & df_igt_bad_long$age_group=="Older", na.rm=TRUE)

older_var_A

older_var_B <- var(df_igt_bad_long$advice_condition=="B" & df_igt_bad_long$age_group=="Older", na.rm=TRUE)

older_var_B

variance_ratio_bad_long <- young_var_none/older_var_A

variance_ratio_bad_long # 1.2 = ratio is fine

```


```{r}
###### ANCOVA ######

# Boxplots

deckab_bxp1 <- ggboxplot(
  df_igt_bad_long, x = "advice_condition", y = "proportion_selected",
  color = "age_group", palette = "jco",
  facet.by = "deck", short.panel.labs = FALSE
  )
deckab_bxp1

# Check outliers

abdecks_outliers <- df_igt_bad_long %>%
  group_by(age_group, advice_condition, deck, block) %>%
  identify_outliers(proportion_selected)

abdecks_outliers
#12 extreme outliers

# Shapiro Wilks test

df_igt_bad_long %>%
  group_by(age_group, advice_condition, deck, block) %>%
  shapiro_test(proportion_selected) 

# Levene's test

df_igt_bad_long %>%
  group_by(deck, block) %>%
  levene_test(proportion_selected ~ age_group*advice_condition)

# Run ANCOVA

abdecks_aov <- aov_ez("id","proportion_selected",df_igt_bad_long,
                      between=c("age_group", "advice_condition"),within=c("deck","block"),
                      covariate = c("stress_score", "anxiety_score", "depression_score",
                                    "education", "matrices"),
                      factorize = FALSE,
                      anova_table = list(es = "pes")
                      )

abdecks_aov

# Main effect of age group

maineffage1 <- emmeans(abdecks_aov, ~age_group)

maineffage1 

df_igt_bad_long %>% group_by(age_group) %>% 
  get_summary_stats(proportion_selected, type = "mean_sd")

# Main effect of advice condition

adviceconditionmain <- emmeans(abdecks_aov, ~advice_condition)

adviceconditionmain

pairs(adviceconditionmain, adjust = "tukey")

df_igt_bad_long %>% group_by(advice_condition) %>% 
  get_summary_stats(proportion_selected, type = "mean_sd")

# Main effect of deck

maineffdeck1 <- emmeans(abdecks_aov, ~deck)

maineffdeck1

df_igt_bad_long %>% group_by(deck) %>% 
  get_summary_stats(proportion_selected, type = "mean_sd")

# Deck by block interaction

deck_block_int <- emmeans(abdecks_aov, ~deck|block)
deck_block_int

pairs(deck_block_int)

# Advice condition by deck by block interaction

adv_deck_block_int <- emmeans(abdecks_aov, ~advice_condition|deck|block)

adv_deck_block_int

pairs(adv_deck_block_int)

```


```{r}
##### Interaction with education covariate #####

lm_edu_deck <- lm(proportion_selected~deck:education, data = df_igt_bad_long)

summary(lm_edu_deck)


```


```{r}
##### Advice condition x deck x block graph #####

abdecks_graph1 <- afex_plot(abdecks_aov, x = "block", trace = "advice_condition", 
                        panel = "deck", error = NULL,
                        data_arg = list(colour = "transparent"), # have to add colour = "transparent" to take out background data
                        point_arg = list(size = 2), line_arg = list(size = .5),
                        factor_levels = list(block = c("1", "2", "3", "4","5"),
                                    advice_condition = c("No Advice", "A Advice",
                                                         "B Advice"),
                                    deck = c("Deck A", "Deck B")), 
                  legend_title = "Advice Condition") + 
  labs(y = "Proportion Selected", x = "Block")+
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "grey"))

abdecks_graph1


#### To save the graph properly
## ggsave("abdecks_graph1.png", device = "png", plot = abdecks_graph1,
##       width = 19, height = 8, units = "cm", 
##       dpi = 600)

```



```{r}

###### Facial EMG Analyses #######

# Prep data

df_losses <- read_csv("2021-12_First_Losses_DeckAB.csv")

df_losses <- clean_names(df_losses)

# Change advice condition values under the advice column (creates duplicates with the Deck column)

df_losses["advice"][df_losses["advice"] == "A"] <- "advice_A"

df_losses["advice"][df_losses["advice"] == "B"] <- "advice_B"

df_losses["advice"][df_losses["advice"] == "None"] <- "no_advice"

# Set factors

df_losses$id <- as.factor(df_losses$id)

df_losses$age_group <- factor(df_losses$age_group, levels = c("Young", "Older"))

df_losses$advice <- factor(df_losses$advice, levels = c("no_advice", "advice_A", "advice_B"))

df_losses$deck <- factor(df_losses$deck, levels = c("A", "B"))

# Spot check info is all in the correct columns

structure(df_losses)

# Descriptives

df_losses %>% 
  group_by(age_group, advice, deck) %>% 
  get_summary_stats(avg_change, type = "mean_sd")

```


```{r}

##### EMG ANOVA #####

# Boxplot

bxpemg <- ggboxplot(
  df_losses, x = "age_group", y = "avg_change",
  color = "advice", palette = "jco",
  facet.by = "deck"
)
bxpemg


# Shapiro-Wilk test

df_losses %>%
  group_by(age_group, advice, deck) %>%
  shapiro_test(avg_change)

# Levene Test

df_losses %>%
  group_by(deck) %>%
  levene_test(avg_change ~ age_group*advice)

# Assumption met.

# Mixed ANOVA Analysis 

frown.aov <- aov_ez("id","avg_change",df_losses,
                      between=c("age_group", "advice"),within=c("deck"),
                      anova_table = list(es = "pes")
                      )
get_anova_table(frown.aov)


df_losses %>% 
  group_by(age_group, advice) %>% 
  get_summary_stats(avg_change, type = "mean_sd")


df_losses %>% 
  group_by(age_group, deck) %>% 
  get_summary_stats(avg_change, type = "mean_sd")

```


```{r}
####### Correlation Analyses ######

# Prep data

# Split into age groups

young_df1 <- filter(df_igt, age_group == "Young")


older_df1 <- filter(df_igt, age_group == "Older")

# Group average proportion of deck a and deck b selections for each person 

young_df2 <- young_df1 %>%
  rowwise() %>%
  mutate(decka = (mean(c_across(decka_block1:decka_block5), na.rm=T)),
       deckb = (mean(c_across(deckb_block1:deckb_block5), na.rm=T)))


older_df2 <- older_df1 %>% 
  rowwise() %>% 
  mutate(decka = (mean(c_across(decka_block1:decka_block5), na.rm=T)),
       deckb = (mean(c_across(deckb_block1:deckb_block5), na.rm=T)))



```


```{r}
### Young adults correlations ###

# Select variables for young adults

young_df2 <- select(young_df2, "education", "dig_span_f", "dig_span_b", "matrices", "stress_score", 
                    "anxiety_score", "depression_score", "decka", "deckb")

structure(young_df2)

ggqqplot(young_df2$matrices, ylab = "matrices")

ggqqplot(young_df2$dig_span_f, ylab = "dig_span_f")

ggqqplot(young_df2$dig_span_b, ylab = "dig_span_b")

ggqqplot(young_df2$stress_score, ylab = "stress_score")

ggqqplot(young_df2$anxiety_score, ylab = "anxiety_score")

ggqqplot(young_df2$depression_score, ylab = "depression_score")

ggqqplot(young_df2$decka, ylab = "decka")

ggqqplot(young_df2$deckb, ylab = "deckb")

# Spearman's correlation matrix due to distribution of data

ya_corr_1 <- rcorr(as.matrix(young_df2), type = "spearman")

ya_corr_1

```


```{r}
### Older adults correlations ###

# Select variables for older adults

older_df2 <- select(older_df2, "education", "dig_span_f", "dig_span_b", "matrices", "stress_score", 
                    "anxiety_score", "depression_score", "decka", "deckb")

structure(older_df2)

ggqqplot(older_df2$matrices, ylab = "matrices")

ggqqplot(older_df2$dig_span_f, ylab = "dig_span_f")

ggqqplot(older_df2$dig_span_b, ylab = "dig_span_b")

ggqqplot(older_df2$stress_score, ylab = "stress_score")

ggqqplot(older_df2$anxiety_score, ylab = "anxiety_score")

ggqqplot(older_df2$depression_score, ylab = "depression_score")

ggqqplot(older_df2$decka, ylab = "decka")

ggqqplot(older_df2$deckb, ylab = "deckb")

# Spearman's correlation

oa_corr_1 <- rcorr(as.matrix(older_df2), type = "spearman")

print(oa_corr_1)

```





